name = "PowerModelsADA"
uuid = "bf5a6c5f-0285-47d6-bb57-79927775d05d"
authors = ["Mohannad Alkhraijah"]
repo = "https://github.com/mkhraijah/PowerModelsADA.jl"
version = "0.1.4"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
DelimitedFiles = "1"
HiGHS = "~0.3, ~1"
InfrastructureModels = "~0.7"
Ipopt = "~0.8, ~0.9, ~1"
JuMP = "~0.22, ~0.23, ~1"
PowerModels = "~0.18.4, ~0.19, 0.21"
Suppressor = "~0.2"
julia = "1.6, 1.8, 1.9"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HiGHS", "Ipopt"]
